INSERT INTO `jci_extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(10377, 'mod_fabrik_form', 'module', 'mod_fabrik_form', '', 0, 1, 1, 0, '{"name":"mod_fabrik_form","type":"module","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"MOD_FABRIK_FORM_XML_DESCRIPTION","group":""}', '{"formid":"0","row_id":"0","usekey":"","template":"default","formmodule_useajax":"1"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10378, 'mod_fabrik_list', 'module', 'mod_fabrik_list', '', 0, 1, 1, 0, '{"name":"mod_fabrik_list","type":"module","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"MOD_FABRIK_LIST_XML_DESCRIPTION","group":""}', '{"useajax":"0","ajax_links":"","radomizerecords":"0","limit":"0","show_nav":"","fabriklayout":"","show-title":"","show_into":"1","show_outro":"1","show_filters":"1"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10379, 'Fabrik Module - Tag Cloud', 'module', 'mod_tagcloud', '', 0, 1, 1, 0, '{"name":"Fabrik Module - Tag Cloud","type":"module","creationDate":"May 2006","author":"Rob Clayburn","copyright":"(C) 2006 Pollen 8 Design Ltd. All rights reserved.","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.0","description":"This module shows a tag cloud from a given data set.","group":""}', '{"moduleclass_sfx":"","@spacer":"","table":"","column":"","filter":"","url":"","css":"","splitter":",","alphabetically":"1","min":"1","max":"20","seperator":" :: "}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10380, 'mod_fabrik_form', 'module', 'mod_fabrik_form', '', 1, 1, 1, 0, '{"name":"mod_fabrik_form","type":"module","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"MOD_FABRIK_FORM_XML_DESCRIPTION","group":""}', '{"formid":"0","row_id":"0","usekey":"","template":"default","formmodule_useajax":"1"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10381, 'mod_fabrik_list', 'module', 'mod_fabrik_list', '', 1, 1, 1, 0, '{"name":"mod_fabrik_list","type":"module","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"MOD_FABRIK_LIST_XML_DESCRIPTION","group":""}', '{"useajax":"","ajax_links":"","radomizerecords":"0","limit":"0","fabriklayout":"default"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10382, 'mod_fabrik_quickicon', 'module', 'mod_fabrik_quickicon', '', 1, 1, 1, 0, '{"name":"mod_fabrik_quickicon","type":"module","creationDate":"May 2013","author":"Fabrik","copyright":"Copyright (C) 2005 - 2013 Fabrik. All rights reserved.","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"MOD_FABRIK_QUICKICON_XML_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10383, 'Fabrik Visualization', 'module', 'mod_fabrik_visualization', '', 1, 1, 1, 0, '{"name":"Fabrik Visualization","type":"module","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"This module shows a Fabrik visualization in Joomlas adminstration pages.","group":""}', '{"id":"0"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10384, 'Fabrik', 'component', 'com_fabrik', '', 1, 1, 1, 0, '{"name":"Fabrik","type":"component","creationDate":"February 2013","author":"Fabrik","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.pollen-8.co.uk","version":"3.1b","description":"COM_FABRIK_XML_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10385, 'plg_fabrik', 'plugin', 'fabrik', 'content', 0, 0, 1, 0, '{"name":"plg_fabrik","type":"plugin","creationDate":"February 2013","author":"Pollen 8 Design Ltd","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_DESCRIPTION","group":""}', '{"botRegex":"fabrik"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10386, 'email', 'plugin', 'email', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_email","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_EMAIL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10387, 'gcalsync', 'plugin', 'gcalsync', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_gcalsync","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_GCALSYNC_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10388, 'geocode', 'plugin', 'geocode', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_geocode","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_GEOCODE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10389, 'gmail', 'plugin', 'gmail', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_gmail","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_GMAIL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10390, 'importcsv', 'plugin', 'importcsv', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_cron_importcsv","type":"plugin","creationDate":"February 2013","author":"Mike Griggs","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"migsby@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_CRON_IMPORTCSV_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10391, 'notification', 'plugin', 'notification', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_notifications","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_NOTIFICATIONS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10392, 'php', 'plugin', 'php', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_php","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_PHP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10393, 'rest', 'plugin', 'rest', 'fabrik_cron', 0, 1, 1, 0, '{"name":"plg_fabrik_cron_rest","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_CRON_REST_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10394, 'access', 'plugin', 'access', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_access","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_ACCESS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10395, 'birthday', 'plugin', 'birthday', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_birthday","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_BIRTHDAY_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10396, 'button', 'plugin', 'button', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_button","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_BUTTON_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10397, 'calc', 'plugin', 'calc', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_calc","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_CALC_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10398, 'captcha', 'plugin', 'captcha', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_captcha","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_CAPTCHA_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10399, 'cascadingdropdown', 'plugin', 'cascadingdropdown', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_cascadingdropdown","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_CDD_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10400, 'checkbox', 'plugin', 'checkbox', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_checkbox","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_CHECKBOX_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10401, 'colourpicker', 'plugin', 'colourpicker', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_colourpicker","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_COLOURPICKER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10402, 'count', 'plugin', 'count', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_count","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_COUNT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10403, 'databasejoin', 'plugin', 'databasejoin', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_databasejoin","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_DBJOIN_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, -1),
(10404, 'plg_fabrik_element_date', 'plugin', 'date', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_date","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_DATE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10405, 'plg_fabrik_element_display', 'plugin', 'display', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_display","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_DISPLAY_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10406, 'plg_fabrik_element_dropdown', 'plugin', 'dropdown', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_dropdown","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_DROPDOWN_DESCRIPTION","group":""}', '{"defaultFieldType":"TEXT"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10407, 'plg_fabrik_element_fbactivity', 'plugin', 'fbactivityfeed', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fbactivity","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FBFEED_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10408, 'plg_fabrik_element_fbcomment', 'plugin', 'fbcomment', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fbcomment","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FBCOMMENT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10409, 'plg_fabrik_element_fblike', 'plugin', 'fblike', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fblike","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FBLIKE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10410, 'plg_fabrik_element_fblikebox', 'plugin', 'fblikebox', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fblikebox","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FBLIKEBOX_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10411, 'plg_fabrik_element_fbrecommendations', 'plugin', 'fbrecommendations', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fbrecommendations","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FBRECOMMENDATION_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10412, 'plg_fabrik_element_field', 'plugin', 'field', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_field","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FIELD_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10413, 'plg_fabrik_element_fileupload', 'plugin', 'fileupload', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_fileupload","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FILEUPLOAD_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10414, 'plg_fabrik_element_folder', 'plugin', 'folder', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_folder","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_FOLDER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10415, 'plg_fabrik_element_googlemap', 'plugin', 'googlemap', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_googlemap","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_GOOGLE_MAP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10416, 'plg_fabrik_element_googleometer', 'plugin', 'googleometer', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_googleometer","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_GOOGLEOMETER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10417, 'plg_fabrik_element_image', 'plugin', 'image', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_image","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_IMAGE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10418, 'plg_fabrik_element_internalid', 'plugin', 'internalid', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_internalid","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_INTERNALID_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10419, 'plg_fabrik_element_ip', 'plugin', 'ip', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_ip","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_IP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10420, 'plg_fabrik_element_jsperiodical', 'plugin', 'jsperiodical', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_jsperiodical","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_JSPERIODICAL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0);
INSERT INTO `jci_extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(10421, 'plg_fabrik_element_kaltura', 'plugin', 'kaltura', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_kaltura","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_KALTURA_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10422, 'plg_fabrik_element_link', 'plugin', 'link', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_link","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_LINK_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10423, 'plg_fabrik_element_notes', 'plugin', 'notes', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_notes","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_NOTES_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10424, 'plg_fabrik_element_password', 'plugin', 'password', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_password","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_PASSWORD_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10425, 'plg_fabrik_element_picklist', 'plugin', 'picklist', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_picklist","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_PICKLIST_DESCRIPTION","group":""}', '{"defaultFieldType":"TEXT"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10426, 'plg_fabrik_element_radiobutton', 'plugin', 'radiobutton', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_radiobutton","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_RADIO_DESCRIPTION","group":""}', '{"defaultFieldType":"TEXT"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10427, 'plg_fabrik_element_rating', 'plugin', 'rating', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_rating","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_RATING_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10428, 'plg_fabrik_element_slider', 'plugin', 'slider', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_slider","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_SLIDER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10429, 'Fabrik Element - Sugar CRM ID', 'plugin', 'sugarid', 'fabrik_element', 0, 1, 1, 0, '{"name":"Fabrik Element - Sugar CRM ID","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"Renders a sugar id field","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10430, 'plg_fabrik_element_textarea', 'plugin', 'textarea', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_textarea","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_TEXTAREA_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10431, 'plg_fabrik_element_thumbs', 'plugin', 'thumbs', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_thumbs","type":"plugin","creationDate":"February 2013","author":"Thomas Spierckel","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"tom@spierckel.net","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_THUMBS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10432, 'plg_fabrik_element_time', 'plugin', 'time', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_time","type":"plugin","creationDate":"February 2013","author":"Jaanus Nurmoja","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"jaanus.nurmoja@gmail.com","authorUrl":"www.facebook.com\\/jaanus.nurmoja","version":"3.1b","description":"PLG_ELEMENT_TIME_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10433, 'plg_fabrik_element_timer', 'plugin', 'timer', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_timer","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_TIMER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10434, 'plg_fabrik_element_timestamp', 'plugin', 'timestamp', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_timestamp","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_TIMESTAMP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10435, 'plg_fabrik_element_user', 'plugin', 'user', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_user","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_USER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10436, 'plg_fabrik_element_usergroup', 'plugin', 'usergroup', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_usergroup","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_USER_GROUP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10437, 'PLG_FABRIK_ELEMENT_VIEWLEVE', 'plugin', 'viewlevel', 'fabrik_element', 0, 1, 1, 0, '{"name":"PLG_FABRIK_ELEMENT_VIEWLEVE","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_VIEWLEVEL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10438, 'plg_fabrik_element_yesno', 'plugin', 'yesno', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_yesno","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_YESNO_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10439, 'plg_fabrik_element_youtube', 'plugin', 'youtube', 'fabrik_element', 0, 1, 1, 0, '{"name":"plg_fabrik_element_youtube","type":"plugin","creationDate":"February 2013","author":"peamak","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"pktom64@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_ELEMENT_YOUTUBE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10440, 'plg_fabrik_form_alphauserpoints', 'plugin', 'alphauserpoints', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_alphauserpoints","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_ALPHAUSERPOINTS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10441, 'plg_fabrik_form_autofill', 'plugin', 'autofill', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_autofill","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_AUTOFILL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10442, 'plg_fabrik_form_clone', 'plugin', 'clone', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_clone","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_CLONE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10443, 'plg_fabrik_form_comment', 'plugin', 'comment', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_comment","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_COMMENT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10444, 'plg_fabrik_form_confirmation', 'plugin', 'confirmation', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_confirmation","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_CONFIRMATION_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10445, 'plg_fabrik_form_email', 'plugin', 'email', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_email","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_EMAIL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10446, 'plg_fabrik_form_exif', 'plugin', 'exif', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_exif","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_EXIF_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10447, 'FTP', 'plugin', 'ftp', 'fabrik_form', 0, 1, 1, 0, '{"name":"FTP","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_EMAIL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10448, 'plg_fabrik_form_juser', 'plugin', 'juser', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_juser","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_JUSER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10449, 'plg_fabrik_form_kunena', 'plugin', 'kunena', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_kunena","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_KUNENA_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10450, 'plg_fabrik_form_limit', 'plugin', 'limit', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_limit","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_LIMIT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10451, 'plg_fabrik_form_logs', 'plugin', 'logs', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_logs","type":"plugin","creationDate":"February 2013","author":"Peamak","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"pktom64@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_LOGS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10452, 'plg_fabrik_form_mailchimp', 'plugin', 'mailchimp', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_mailchimp","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_MAILCHIMP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10453, 'plg_fabrik_form_notification', 'plugin', 'notification', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_notification","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_NOTIFICATION_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10454, 'plg_fabrik_form_paginate', 'plugin', 'paginate', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_paginate","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_PAGINATE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10455, 'plg_fabrik_form_paypal', 'plugin', 'paypal', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_paypal","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_PAYPAL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10456, 'plg_fabrik_form_php', 'plugin', 'php', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_php","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_PHP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10457, 'plg_fabrik_form_receipt', 'plugin', 'receipt', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_receipt","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_RECEIPT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10458, 'plg_fabrik_form_redirect', 'plugin', 'redirect', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_redirect","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_REDIRECT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10459, 'plg_fabrik_form_rest', 'plugin', 'rest', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_rest","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_REST_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10460, 'plg_fabrik_form_salesforce', 'plugin', 'salesforce', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_salesforce","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_SALESFORCE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10461, 'plg_fabrik_form_sms', 'plugin', 'sms', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_sms","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_SMS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10462, 'plg_fabrik_form_subscriptions', 'plugin', 'subscriptions', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_subscriptions","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_SUBSCRIPTIONS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10463, 'plg_fabrik_form_twitter', 'plugin', 'twitter', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_twitter","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_TWITTER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10464, 'PLG_FABRIK_FORM_UPSERT', 'plugin', 'upsert', 'fabrik_form', 0, 1, 1, 0, '{"name":"PLG_FABRIK_FORM_UPSERT","type":"plugin","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"PLG_FORM_UPSERT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10465, 'plg_fabrik_form_vbforum', 'plugin', 'vbforum', 'fabrik_form', 0, 1, 1, 0, '{"name":"plg_fabrik_form_vbforum","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FORM_VBFORUM_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10466, 'plg_fabrik_list_candeleterow', 'plugin', 'candeleterow', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_candeleterow","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_CANDELETEROW_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10467, 'plg_fabrik_list_caneditrow', 'plugin', 'caneditrow', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_caneditrow","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_CANEDITROW_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10468, 'plg_fabrik_list_copy', 'plugin', 'copy', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_copy","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_COPY_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10469, 'plg_fabrik_list_download', 'plugin', 'download', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_download","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_DOWNLOAD_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10470, 'plg_fabrik_list_email', 'plugin', 'email', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_email","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.o.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_EMAIL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10471, 'plg_fabrik_list_filter_view', 'plugin', 'filter_view', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_filter_view","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_FILTER_VIEW_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10472, 'plg_fabrik_list_inlineedit', 'plugin', 'inlineedit', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_inlineedit","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_INLINEEDIT_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10473, 'plg_fabrik_list_js', 'plugin', 'js', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_js","type":"plugin","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"PLG_LIST_JS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10474, 'Fabrik List - Example', 'plugin', 'list_example', 'fabrik_list', 0, 1, 1, 0, '{"name":"Fabrik List - Example","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"Example list plugin","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10475, 'plg_fabrik_list_listcsv', 'plugin', 'listcsv', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_listcsv","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_PHP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10476, 'plg_fabrik_list_order', 'plugin', 'order', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_order","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_ORDER_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10477, 'plg_fabrik_list_php', 'plugin', 'php', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_php","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_PHP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10478, 'plg_fabrik_list_php_events', 'plugin', 'php_events', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_php_events","type":"plugin","creationDate":"February 2013","author":"Mauro H. Leggieri","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"mxmauro@mauroleggieri.com.ar","authorUrl":"www.yodespotrico.com.ar","version":"3.1b","description":"PLG_LIST_PHP_EVENTS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10479, 'plg_fabrik_list_radius_search', 'plugin', 'radius_search', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_radius_search","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_RADIUS_SEARCH_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10480, 'plg_fabrik_list_update_col', 'plugin', 'update_col', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_update_col","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_UPDATE_COL_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10481, 'plg_fabrik_list_webservice', 'plugin', 'webservice', 'fabrik_list', 0, 1, 1, 0, '{"name":"plg_fabrik_list_webservice","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_LIST_WEBSERVICE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10482, 'PLG_FABRIK_VALIDATIONRULE_AKISMET', 'plugin', 'akismet', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"PLG_FABRIK_VALIDATIONRULE_AKISMET","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_AKISMET_DESCRIPTION","group":""}', '{"icon":"filter"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10483, 'plg_fabrik_validationrule_areuniquevalues', 'plugin', 'areuniquevalues', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_areuniquevalues","type":"plugin","creationDate":"February 2013","author":"Lieven Gryp","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"lieven.gryp@telenet.be","authorUrl":"www.acpegasus.be","version":"3.1b","description":"PLG_VALIDATIONRULE_AREUNIQUEVALUES_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10484, 'plg_fabrik_validationrule_emailexists', 'plugin', 'emailexists', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_emailexists","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_EMAILEXISTS_DESCRIPTION","group":""}', '{"icon":"envelope"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10485, 'plg_fabrik_validationrule_isalphanumeric', 'plugin', 'isalphanumeric', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isalphanumeric","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISALPHANUMERIC_DESCRIPTION","group":""}', '{"icon":"font"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10486, 'plg_fabrik_validationrule_isemail', 'plugin', 'isemail', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isemail","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISEMAIL_DESCRIPTION","group":""}', '{"icon":"envelope"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10487, 'plg_fabrik_validationrule_isgreaterorlessthan', 'plugin', 'isgreaterorlessthan', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isgreaterorlessthan","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISGREATERORLESSTHAN_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10488, 'plg_fabrik_validationrule_isnot', 'plugin', 'isnot', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isnot","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISNOT_DESCRIPTION","group":""}', '{"icon":"exclamation-sign"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10489, 'plg_fabrik_validationrule_isnumeric', 'plugin', 'isnumeric', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isnumeric","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISNUMERIC_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10490, 'plg_fabrik_validationrule_isuniquevalue', 'plugin', 'isuniquevalue', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_isuniquevalue","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_ISUNIQUEVALUE_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10491, 'plg_fabrik_validationrule_notempty', 'plugin', 'notempty', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_notempty","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_NOTEMPTY_DESCRIPTION","group":""}', '{"icon":"eye-open"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10492, 'plg_fabrik_validationrule_openprovider', 'plugin', 'openprovider', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_openprovider","type":"plugin","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"PLG_VALIDATIONRULE_OPENPROVIDER_DESCRIPTION","group":""}', '{"icon":"globe"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10493, 'plg_fabrik_validationrule_php', 'plugin', 'php', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_php","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_PHP_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10494, 'plg_fabrik_validationrule_regex', 'plugin', 'regex', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_regex","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_REGEX_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10495, 'plg_fabrik_validationrule_specialchars', 'plugin', 'specialchars', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_specialchars","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_SPECIALCHARS_DESCRIPTION","group":""}', '{"icon":"star"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10496, 'plg_fabrik_validationrule_userexists', 'plugin', 'userexists', 'fabrik_validationrule', 0, 1, 1, 0, '{"name":"plg_fabrik_validationrule_userexists","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VALIDATIONRULE_USEREXISTS_DESCRIPTION","group":""}', '{"icon":"user"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10497, 'plg_fabrik_visualization_approvals', 'plugin', 'approvals', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_approvals","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_APPROVALS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10498, 'plg_fabrik_visualization_calendar', 'plugin', 'calendar', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_calendar","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_CALENDAR_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10499, 'plg_fabrik_visualization_chart', 'plugin', 'chart', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_chart","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_CHART_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10500, 'plg_fabrik_visualization_coverflow', 'plugin', 'coverflow', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_coverflow","type":"plugin","creationDate":"May 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.0.8","description":"PLG_VISUALIZATION_COVERFLOW_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10501, 'plg_fabrik_visualization_fusion_gantt_chart', 'plugin', 'fusion_gantt_chart', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_fusion_gantt_chart","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_FUSION_GANTT_CHART_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10502, 'plg_fabrik_visualization_fusioncharts', 'plugin', 'fusionchart', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_fusioncharts","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_FUSIONCHARTS_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10503, 'plg_fabrik_visualization_googlemap', 'plugin', 'googlemap', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_googlemap","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_GOOGLEMAP_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10504, 'plg_fabrik_visualization_media', 'plugin', 'media', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_media","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_MEDIA_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10505, 'plg_fabrik_visualization_nvd3_chart', 'plugin', 'nvd3_chart', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_nvd3_chart","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_NVD3_CHART_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10506, 'plg_fabrik_visualization_slideshow', 'plugin', 'slideshow', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_slideshow","type":"plugin","creationDate":"February 2013","author":"Hugh Messenger","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"hugh.messenger@gmail.com","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_SLIDESHOW_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10507, 'plg_fabrik_visualization_timeline', 'plugin', 'timeline', 'fabrik_visualization', 0, 1, 1, 0, '{"name":"plg_fabrik_visualization_timeline","type":"plugin","creationDate":"February 2013","author":"Rob Clayburn","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_VISUALIZATION_TIMELINE_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10508, 'plg_fabrik_search', 'plugin', 'fabrik', 'search', 0, 0, 1, 0, '{"name":"plg_fabrik_search","type":"plugin","creationDate":"February 2013","author":"Rob Claybrun","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.fabrikar.com","version":"3.1b","description":"PLG_FABRIK_SEARCH_DESCRIPTION","group":""}', '{"search_limit":"50","search_section_heading":"Fabrik\\/record"}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10509, 'plg_fabrik_system', 'plugin', 'fabrik', 'system', 0, 1, 1, 0, '{"name":"plg_fabrik_system","type":"plugin","creationDate":"February 2013","author":"Fabrikar.com","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.pollen-8.co.uk","version":"3.1b","description":"PLG_FABRIK_SYSTEM_DESCRIPTION","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0),
(10510, 'System - Fabrik Scheduled Tasks', 'plugin', 'fabrikcron', 'system', 0, 0, 1, 0, '{"name":"System - Fabrik Scheduled Tasks","type":"plugin","creationDate":"February 2013","author":"Pollen 8","copyright":"(C) 2005-2013 fabrikar.com","authorEmail":"rob@pollen-8.co.uk","authorUrl":"www.pollen-8.co.uk","version":"3.1b","description":"Runs Fabrik scheduled tasks","group":""}', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0);

CREATE TABLE IF NOT EXISTS `jci_fabrik_connections` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`host` VARCHAR(255) NOT NULL,
	`user` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`database` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`published` INT(1) NOT NULL default '0',
	`checked_out` INT(4) NOT NULL,
	`checked_out_time` DATETIME,
	`default` INT(1) NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_cron` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`label` VARCHAR(100) NOT NULL,
	`frequency` SMALLINT(6) NOT NULL,
	`unit` VARCHAR(15) NOT NULL,
	`created` DATETIME NOT NULL,
	`created_by` INT(6) NOT NULL,
	`created_by_alias` VARCHAR(30) NOT NULL,
	`modified` DATETIME NOT NULL,
	`modified_by` VARCHAR(30) NOT NULL,
	`checked_out` INT(6) NOT NULL,
	`checked_out_time` DATETIME NOT NULL,
	`published` TINYINT(1) NOT NULL,
	`plugin` VARCHAR(50) NOT NULL,
	`lastrun` DATETIME NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_elements` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`group_id` INT(4) NOT NULL,
	`plugin` VARCHAR(100) NOT NULL,
	`label` TEXT,
	`checked_out` INT(11) NOT NULL,
	`checked_out_time` datetime NOT NULL,
	`created` datetime NOT NULL,
	`created_by` INT(11) NOT NULL,
	`created_by_alias` varchar(100) NOT NULL,
	`modified` datetime NOT NULL,
	`modified_by` INT(11) NOT NULL,
	`width` INT(4) NOT NULL,
	`height` INT(4) NOT NULL default '0',
	`default` TEXT NOT NULL,
	`hidden` INT(1) NOT NULL,
	`eval` INT(1) NOT NULL,
	`ordering` INT(4) NOT NULL,
	`show_in_list_summary` INT(1), 
	`filter_type` VARCHAR (20),
	`filter_exact_match` INT(1),
	`published` INT(1) NOT NULL default '0',
	`link_to_detail` INT(1) NOT NULL default '0',
	`primary_key` INT(1) NOT NULL default '0',
	`auto_increment` INT(1) NOT NULL default '0',
	`access` INT(1) NOT NULL default '0',
	`use_in_page_title` INT(1) NOT NULL default '0',
	`parent_id` MEDIUMINT(6) NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_formgroup` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`form_id` INT(4) NOT NULL,
	`group_id` INT(4) NOT NULL,
	`ordering` INT(4) NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_forms` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`label` VARCHAR(255) NOT NULL,
	`record_in_database` INT(4) NOT NULL,
	`error` VARCHAR(150) NOT NULL,
	`intro` TEXT NOT NULL,
	`created` datetime NOT NULL,
	`created_by` INT(11) NOT NULL,
	`created_by_alias` VARCHAR(100) NOT NULL,
	`modified` datetime NOT NULL,
	`modified_by` INT(11) NOT NULL,
	`checked_out` INT(11) NOT NULL,
	`checked_out_time` datetime NOT NULL,
	`publish_up` DATETIME, 
	`publish_down` DATETIME,
	`reset_button_label` VARCHAR (100) NOT NULL,
	`submit_button_label` VARCHAR (100) NOT NULL,
	`form_template` varchar(255), 
	`view_only_template` varchar(255),
	`published` INT(1) NOT NULL DEFAULT 0,
	`private` TINYINT(1) NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_form_sessions` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`hash` VARCHAR(255) NOT NULL,
	`user_id` INT(6) NOT NULL,
	`form_id` INT(6) NOT NULL,
	`row_id` INT(10) NOT NULL,
	`last_page` INT(4) NOT NULL,
	`referring_url` VARCHAR(255) NOT NULL,
	`data` TEXT NOT NULL,
	`time_date` TIMESTAMP NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_groups` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`css` TEXT NOT NULL,
	`label` VARCHAR(100) NOT NULL,
	`published` INT(1) NOT NULL default '0',
	`created` datetime NOT NULL,
	`created_by` INT(11) NOT NULL,
	`created_by_alias` VARCHAR(100) NOT NULL,
	`modified` datetime NOT NULL,
	`modified_by` INT(11) NOT NULL,
	`checked_out` INT(11) NOT NULL,
	`checked_out_time` datetime NOT NULL,
	`is_join` INT(1) NOT NULL DEFAULT '0',
	`private` TINYINT(1) NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_joins` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`list_id` INT(6) NOT NULL,
	`element_id` INT(6) NOT NULL,
	`join_from_table` VARCHAR(255) NOT NULL,
	`table_join` VARCHAR(255) NOT NULL,
	`table_key` VARCHAR(255) NOT NULL,
	`table_join_key` VARCHAR(255) NOT NULL, 
	`join_type` VARCHAR(255) NOT NULL,
	`group_id` INT(10) NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_jsactions` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`element_id` INT(10) NOT NULL, 
	`action` VARCHAR(255) NOT NULL,
	`code` TEXT NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `jci_fabrik_lists` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`label` VARCHAR (255)  NOT NULL,
	`introduction` TEXT  NOT NULL,
	`form_id` INT(4) NOT NULL,
	`db_table_name` VARCHAR(255) NOT NULL,
	`db_primary_key` VARCHAR(255) NOT NULL,
	`auto_inc` INT(1) NOT NULL,
	`connection_id` INT(6)  NOT NULL,
	`created` DATETIME, 
	`created_by` INT(4) NOT NULL, 
	`created_by_alias` VARCHAR(255) NOT NULL, 
	`modified` DATETIME,
	`modified_by` INT(4) NOT NULL,
	`checked_out` INT(4) NOT NULL,
	`checked_out_time` DATETIME, 
	`published` INT(1) NOT NULL DEFAULT 0,
	`publish_up` DATETIME, 
	`publish_down` DATETIME, 
	`access` INT(4) NOT NULL, 
	`hits` INT(4) NOT NULL,
	`rows_per_page` INT(5) NOT NULL,
	`template` varchar (255) NOT NULL,
	`order_by` varchar (255) NOT NULL,
	`order_dir` varchar(255) NOT NULL default 'ASC',
	`filter_action` varchar(30) NOT NULL, 
	`group_by` VARCHAR(255) NOT NULL, 
	`private` TINYINT(1) NOT NULL DEFAULT '0',
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_log` (
	`id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`timedate_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`flag` SMALLINT(3) NOT NULL,
	`referring_url` VARCHAR(255) NOT NULL,
	`message_source` VARCHAR(255) NOT NULL,
	`message_type` CHAR(60) NOT NULL,
	`message` TEXT NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_packages` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`external_ref` VARCHAR(255) NOT NULL,
	`label` VARCHAR(255) NOT NULL,
	`component_name` VARCHAR(100) NOT NULL,
	`version` VARCHAR(10) NOT NULL,
	`published` TINYINT(1) NOT NULL,
	`checked_out` INT(4) NOT NULL,
	`checked_out_time` DATETIME,
	`created` DATETIME NOT NULL,
	`modified` DATETIME NOT NULL,
	`modified_by` INT(6) NOT NULL,
	`template` VARCHAR(255) NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_validations` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`element_id` INT(4) NOT NULL,
	`validation_plugin` VARCHAR (100)  NOT NULL,
	 `message` varchar(255) null,
	`client_side_validation` INT(1) NOT NULL default 0,
	`checked_out` INT(4) NOT NULL,
	`checked_out_time` DATETIME, 
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `jci_fabrik_visualizations` (
	`id` INT(6) NOT NULL AUTO_INCREMENT,
	`plugin` VARCHAR(100) NOT NULL,
	`label` VARCHAR(255) NOT NULL,
	`intro_text` TEXT NOT NULL,
	`created` DATETIME NOT NULL,
	`created_by` INT(11) NOT NULL,
	`created_by_alias` VARCHAR(100) NOT NULL,
	`modified` DATETIME NOT NULL,
	`modified_by` INT(11) NOT NULL,
	`checked_out` INT(11) NOT NULL,
	`checked_out_time` DATETIME NOT NULL,
	`publish_up` DATETIME NOT NULL,
	`publish_down` DATETIME NOT NULL,
	`published` INT(1) NOT NULL,
	`access` INT(6) NOT NULL,
	`params` TEXT NOT NULL,
	PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `jci_fabrik_connections` (`id`, `host`, `user`, `password`, `database`, `description`, `published`, `checked_out`, `checked_out_time`, `default`, `params`) VALUES
(1, 'localhost', 'fabrikar_ci', '63 8 7 83A3B 93B B6E2F21', 'fabrikar_ci', 'default', 1, 0, '0000-00-00 00:00:00', 1, '{"encryptedPw":true}');

INSERT INTO `jci_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) VALUES
(102, 'main', 'Fabrik', 'fabrik', '', 'fabrik', 'index.php?option=com_fabrik', 'component', 0, 1, 1, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/fabrik.png', 0, '', 47, 64, 0, '', 1),
(103, 'main', 'com_fabrik_lists', 'com-fabrik-lists', '', 'fabrik/com-fabrik-lists', 'index.php?option=com_fabrik&view=lists', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/lists.png', 0, '', 48, 49, 0, '', 1),
(104, 'main', 'com_fabrik_forms', 'com-fabrik-forms', '', 'fabrik/com-fabrik-forms', 'index.php?option=com_fabrik&view=forms', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/forms.png', 0, '', 50, 51, 0, '', 1),
(105, 'main', 'com_fabrik_groups', 'com-fabrik-groups', '', 'fabrik/com-fabrik-groups', 'index.php?option=com_fabrik&view=groups', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/groups.png', 0, '', 52, 53, 0, '', 1),
(106, 'main', 'com_fabrik_elements', 'com-fabrik-elements', '', 'fabrik/com-fabrik-elements', 'index.php?option=com_fabrik&view=elements', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/elements.png', 0, '', 54, 55, 0, '', 1),
(107, 'main', 'com_fabrik_visualizations', 'com-fabrik-visualizations', '', 'fabrik/com-fabrik-visualizations', 'index.php?option=com_fabrik&view=visualizations', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/visualizations.png', 0, '', 56, 57, 0, '', 1),
(108, 'main', 'com_fabrik_packages', 'com-fabrik-packages', '', 'fabrik/com-fabrik-packages', 'index.php?option=com_fabrik&view=packages', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/packages.png', 0, '', 58, 59, 0, '', 1),
(109, 'main', 'com_fabrik_connections', 'com-fabrik-connections', '', 'fabrik/com-fabrik-connections', 'index.php?option=com_fabrik&view=connections', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/connections.png', 0, '', 60, 61, 0, '', 1),
(110, 'main', 'com_fabrik_schedule', 'com-fabrik-schedule', '', 'fabrik/com-fabrik-schedule', 'index.php?option=com_fabrik&view=crons', 'component', 0, 102, 2, 10384, 0, '0000-00-00 00:00:00', 0, 1, '../administrator/components/com_fabrik/images/schedules.png', 0, '', 62, 63, 0, '', 1);


